# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13e1708b318e637cca7d4ed588999a8d328d636c9d63989993ee64887d36c0941461e9ec591aba719f16ccb6d16bb8808700c59add87acc7b08fe1d48985f4dd

test:
  secret_key_base: 5bffdcb041a379221c5aacec2269573cd20bfe38ef34f1e09d64605ee9e173992d2ed735b122ef90cb836176a75d93c541dba9b752444b55b39d85bc4ca2d136

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
